name: 🔓 Security Vulnerability
description: Report a security vulnerability
title: "vulnerability: "
labels: ["vulnerability"]
assignees:
  - bennett-sh
body:
  - type: markdown
    attributes:
      value: |
        # Security Vulnerability
        Use this form to report a security vulnerability you've discovered.
        
        ## Public Posting Notice
        Your responses will be publicly posted. If you think that the vulnerability you've discovered is so impactful that it's unresponsible to publicly post it, feel free to ask any maintainer for their contact information. 
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the vulnerability you discovered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the vulnerability
      description: Please provide a clear and concise description of the security vulnerability you have identified.
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Please describe the potential impact of this vulnerability.
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Please select the severity level of the security vulnerability you are reporting. S3 is the highest and H0 is the lowest severity level.
      options:
        - S3
        - S2
        - S1
        - S0
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Steps
      description: Please provide the exact steps necessary to reproduce the vulnerability, including any code or configurations that are required.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Please provide a detailed explanation of any proposed solutions you may have to address this vulnerability.
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Please provide any additional information that may be relevant, such as affected versions, operating systems, or configurations.
