name: Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Cache
        id: cache
        uses: actions/cache@v2.1.6
        with:
          path: node_modules
          key: buildCachev25

      - name: Install PNPM
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Setup Repo Builder
        run: |
          cd builder
          pnpm install
          pnpm run build

      - name: Generate Repo Data
        run: |
          pnpm run generateCode
          cd ..

      - name: Build
        run: |
          pnpm run build

      - name: Run tests
        run: |
          pnpm run test
